# Generated by Django 3.2.11 on 2022-01-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_announcement_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='currency',
            field=models.CharField(choices=[('PLN', 'PLN'), ('USD', 'USD'), ('NOK', 'NOK'), ('RUB', 'RUB'), ('EUR', 'EUR')], default='PLN', max_length=3),
            preserve_default=False,
        ),
    ]
