# Generated by Django 3.2.11 on 2022-02-13 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0011_announcement_usr_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='usr_profile',
        ),
    ]
